name: GitHub CI
on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  linux64_build:
    name: Linux x86_64 Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: |
        docker run -v $GITHUB_WORKSPACE:/root/workdir -e TRAVIS_BRANCH=action -e TRAVIS_TAG=action multiarch/alpine:amd64-latest-stable /bin/sh -c "apk add bash git && cd /root/workdir && bash scripts/build.alpine.release.sh"
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: stairspeedtest_reborn_linux64
        path: stairspeedtest/
    - name: Package Release
      run: tar czf stairspeedtest_reborn_linux64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      with:
        files: stairspeedtest_reborn_linux64.tar.gz
        draft: true

  macos_build:
    name: macOS Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add commit id into version
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: SHA=$(git rev-parse --short HEAD) && sed -i -e 's/\(v[0-9]\.[0-9]\.[0-9]\)/\1-'"$SHA"'/' src/version.h
    - name: Build
      run: |
        bash scripts/build.macos.release.sh
        bash scripts/build.macos.clients.sh
        mv base stairspeedtest
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: stairspeedtest_reborn_darwin64
        path: stairspeedtest/
    - name: Package Release
      run: tar czf stairspeedtest_reborn_darwin64.tar.gz stairspeedtest
    - name: Draft Release
      uses: softprops/action-gh-release@v1
      with:
        files: stairspeedtest_reborn_darwin64.tar.gz
        draft: true
